import { Box, styled } from '@mui/material';
import Head from 'next/head';
import { ReactNode } from 'react';

type Props = {
  title: string;
  children?: ReactNode;
  header: ReactNode;
  footer?: ReactNode;
};

const StyledWrapper = styled(Box)`
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  height: 100%;
`;

const Layout = ({ title, children, header, footer }: Props) => {
  return (
    <>
      <Head>
        {/* TODO: use next-seo */}
        <title>{title}</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
      </Head>
      <StyledWrapper>
        {header}
        {children}
      </StyledWrapper>
      {footer}
    </>
  );
};

export default Layout;
