name: 'code-review'
on:
  pull_request:
    branches:
      - master
      - develop
    types: [opened, synchronize, reopened]
jobs:
  code-review:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stellarimssoftware/AutoReviewer@main
        env:
          NODE_OPTIONS: '--experimental-fetch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          exclude_files: '*.d.ts,*.d.ts.map,*.lock' # optionally exclude files based on a wildcard expression. 
          model_name: 'gpt-4'